### PR TITLE
fix memory leak in request handler

### PR DESCRIPTION
**Pull request by Reasno**
There was an observable memory leak in the original code.

### CODE REVIEW

**Comment by Reasno** [comment]
Also updated minio api so that docker build can proceed.

**Comment by alexellis** [comment]
Hi there thanks for your interest in my project. 

I can't see any memory leak or any details of how you found one or why this change fixes it?

Can you give some context please?

Alex

**Comment by Reasno** [comment]
After running this docker image for a little more than a week with consistent load (mostly PUT), I noticed my container consumed more than 4G memory and it is still growing. By looking into details I can see the growth of memory is on par with the total file size I uploaded through this container. So it appeared the upload handler were not recycling properly. This result is repeatable so you can try it yourself.

With some digging I can see the problem is explained in this blog: http://pliutau.com/memory_leaks_in_mux_router/

This PR may not be the most elegant solution but it worked for me. If there was a better fix please just disregard my PR. 

Thanks

**Comment by Reasno** [comment]
Some more digging: https://github.com/gorilla/sessions/pull/110

> because mux.Vars() and this session library still uses gorilla context..so whoever uses mux or this library will be running into this issue

**Comment by alexellis** [comment]
Hi @Reasno can we fix this?

Would you like to re-test your PR and update to Go 1.11?

I use `go dep`, rather than Go modules for my projects.

https://golang.github.io/dep/docs/introduction.html

Alex

**Pull request closed without merging**
